name: Название дефекта
description: Краткое описание дефекта
title: "[Ошибка]: Название ошибки"
labels: ["bug"]
body:
  - type: textarea
    id: descriptionId
    attributes:
      label: Описание ошибки
      description: Подробное описание дефекта
      placeholder: Опишите проблему подробно
    validations:
      required: true
  - type: markdown
    id: stepsToReproduceId
    attributes:
      label: Шаги воспроизведения
      description: Опишите шаги, которые необходимо выполнить для воспроизведения ошибки
      placeholder: Шаги для воспроизведения проблемы
    validations:
      required: true
