name: Отчёт об ошибке
description: Краткое описание дефекта
title: "[Ошибка]: Название ошибки"
labels: ["bug"]
body:
  - type: textarea
    id: descriptionId
    attributes:
      label: Описание ошибки
      description: Подробное описание дефекта
      placeholder: Опишите проблему подробно
    validations:
      required: true
  - type: textarea
    id: stepsToReproduceId
    attributes:
      label: Шаги воспроизведения
      description: Опишите шаги, которые необходимо выполнить для воспроизведения ошибки
      placeholder: Шаги для воспроизведения проблемы
    validations:
      required: true
  - type: textarea
    id: expectedResultId
    attributes:
      label: Ожидаемый результат
      description: "Опишите, что должно произойти при выполнении шагов."
      placeholder: "Ожидаемый результат"
    validations:
      required: true
  - type: textarea
    id: actualResultId
    attributes:
      label: Фактический результат
      description: "Опишите, что произошло на самом деле."
      placeholder: "Фактический результат"
    validations:
      required: true
  - type: textarea
    id: additionalInfoId
    attributes:
      label: Дополнительная информация
      description: Приложите дополнительные материалы
    validations:
      required: true
  - type: textarea
    id: environmentId
    attributes:
      label: Среда выполнения
      description: "Укажите среду, в которой возникла ошибка (например, ОС, браузер)."
      placeholder: "Windows 10, Chrome 95"
    validations:
      required: true
  - type: dropdown
    id: severityId
    attributes:
      label: Приоритет
      description: "Выберите уровень серьезности дефекта."
      options:
        - label: "Критический"
          required: false
        - label: "Высокий"
          required: false
        - label: "Средний"
          required: false
        - label: "Низкий"
          required: false
